/**
 * NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
 * Do not edit the file manually.
 *
 * Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
 * Copyright 2022 HiRez Studios
 * SPDX-License-Identifier: Apache-2.0
 *
 * Rally Here APIs
 * version: 0.1.0
 * Rally Here APIs
 */

#pragma once

#include "RallyHereAPIBaseModel.h"
#include "RallyHereAPIHelpers.h"
#include "PortalTokenDetailsGrantType.h"
#include "BodyGetPortalTokenDetailsV1PortaltokenDetailsPost.generated.h"

/*
* FRHAPI_BodyGetPortalTokenDetailsV1PortaltokenDetailsPost
*
* 
*/
USTRUCT(BlueprintType)
struct RALLYHEREAPI_API FRHAPI_BodyGetPortalTokenDetailsV1PortaltokenDetailsPost : public FRHAPI_Model
{
    GENERATED_BODY()

    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override final;
    void WriteJson(TSharedRef<TJsonWriter<>>& Writer) const override final;

    UPROPERTY(BlueprintReadOnly, Category = "RallyHere")
    ERHAPI_PortalTokenDetailsGrantType GrantType{  };
    ERHAPI_PortalTokenDetailsGrantType& GetGrantType() { return GrantType; }
    const ERHAPI_PortalTokenDetailsGrantType& GetGrantType() const { return GrantType; }
    void SetGrantType(ERHAPI_PortalTokenDetailsGrantType NewValue) { GrantType = NewValue;  }

    /* token or secret used to authenticate the provided grant type */
    UPROPERTY(BlueprintReadOnly, Category = "RallyHere")
    FString PortalAccessToken{  };
    FString& GetPortalAccessToken() { return PortalAccessToken; }
    const FString& GetPortalAccessToken() const { return PortalAccessToken; }
    void SetPortalAccessToken(FString NewValue) { PortalAccessToken = NewValue;  }
};
