// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "RallyHereAPIBaseModel.h"
#include "RallyHereAPIHelpers.h"
#include "InstanceHealthStatus.h"
#include "InstanceHealthStatusResponse.generated.h"

/** @defgroup RHAPI_InstanceHealthStatusResponse RallyHere API Model InstanceHealthStatusResponse
 *  @{
 */

/**
 * @brief Response body for an instance health check
 */
USTRUCT(BlueprintType)
struct RALLYHEREAPI_API FRHAPI_InstanceHealthStatusResponse : public FRHAPI_Model
{
	GENERATED_BODY()

	/**
	* @brief Fills this object with data from the passed in JSON
	*
	* @param [in] JsonValue Data from the API call.
	*
	* @return true if parsing of the JSON data was successful.
	*/
	virtual bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override final;

	/**
	* @brief Writes the data from this object into the specified JSON Writer stream
	*
	* @param [in] Writer JSON Writer stream to push .
	*/
	virtual void WriteJson(TSharedRef<TJsonWriter<>>& Writer) const override final;

	/** @brief The new health status of the instance. It may not match the status sent up if too few health checks are being recieved */
	UPROPERTY(BlueprintReadWrite, Category = "RallyHere")
	ERHAPI_InstanceHealthStatus UpdatedInstanceHealth{  };
	/** @brief Gets the value of UpdatedInstanceHealth */
	ERHAPI_InstanceHealthStatus& GetUpdatedInstanceHealth() { return UpdatedInstanceHealth; }
	/** @brief Gets the value of UpdatedInstanceHealth */
	const ERHAPI_InstanceHealthStatus& GetUpdatedInstanceHealth() const { return UpdatedInstanceHealth; }
	/** @brief Sets the value of UpdatedInstanceHealth */
	void SetUpdatedInstanceHealth(const ERHAPI_InstanceHealthStatus& NewValue) { UpdatedInstanceHealth = NewValue;   }
	/** @brief Sets the value of UpdatedInstanceHealth using move semantics */
	void SetUpdatedInstanceHealth(ERHAPI_InstanceHealthStatus&& NewValue) { UpdatedInstanceHealth = NewValue;   }
};

/** @} */
