// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "RallyHereAPIBaseModel.h"
#include "RallyHereAPIHelpers.h"
#include "PublicKey.h"
#include "PublicKeyList.generated.h"

/** @defgroup RHAPI_PublicKeyList RallyHere API Model PublicKeyList
 *  @{
 */

/**
 * @brief List of public keys for verifying Access Token JWTs.  This is in the JWK Set format as defined in https://datatracker.ietf.org/doc/html/rfc7517#section-5
 */
USTRUCT(BlueprintType)
struct RALLYHEREAPI_API FRHAPI_PublicKeyList : public FRHAPI_Model
{
	GENERATED_BODY()

	/**
	* @brief Fills this object with data from the passed in JSON
	*
	* @param [in] JsonValue Data from the API call.
	*
	* @return true if parsing of the JSON data was successful.
	*/
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override final;

	/**
	* @brief Writes the data from this object into the specified JSON Writer stream
	*
	* @param [in] Writer JSON Writer stream to push .
	*/
	void WriteJson(TSharedRef<TJsonWriter<>>& Writer) const override final;

	/** @brief List of public keys for verifying Access Token JWTs */
	UPROPERTY(BlueprintReadWrite, Category = "RallyHere")
	TArray<FRHAPI_PublicKey> Keys{  };
	/** @brief Gets the value of Keys */
	TArray<FRHAPI_PublicKey>& GetKeys() { return Keys; }
	/** @brief Gets the value of Keys */
	const TArray<FRHAPI_PublicKey>& GetKeys() const { return Keys; }
	/** @brief Sets the value of Keys */
	void SetKeys(const TArray<FRHAPI_PublicKey>& NewValue) { Keys = NewValue;  }
	/** @brief Sets the value of Keys using move semantics */
	void SetKeys(TArray<FRHAPI_PublicKey>&& NewValue) { Keys = NewValue;  }
};

/** @} */
