# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Enhancements and Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
