// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "DevMapSelectionListEntryUpdateRequest.h"
#include "RallyHereDeveloperAPIModule.h"
#include "RallyHereDeveloperAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereDeveloperAPI::ToStringFormatArg;
using RallyHereDeveloperAPI::WriteJsonValue;
using RallyHereDeveloperAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for FRHAPI_DevMapSelectionListEntryUpdateRequest

void FRHAPI_DevMapSelectionListEntryUpdateRequest::WriteJson(TSharedRef<TJsonWriter<>>& Writer) const
{
    Writer->WriteObjectStart();
    if (MapWeight_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("map_weight"));
        RallyHereDeveloperAPI::WriteJsonValue(Writer, MapWeight_Optional);
    }
    if (MapId_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("map_id"));
        RallyHereDeveloperAPI::WriteJsonValue(Writer, MapId_Optional);
    }
    Writer->WriteObjectEnd();
}

bool FRHAPI_DevMapSelectionListEntryUpdateRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    const TSharedPtr<FJsonValue> JsonMapWeightField = (*Object)->TryGetField(TEXT("map_weight"));
    if (JsonMapWeightField.IsValid() && !JsonMapWeightField->IsNull())
    {
        MapWeight_IsSet = TryGetJsonValue(JsonMapWeightField, MapWeight_Optional);
        ParseSuccess &= MapWeight_IsSet;
    }
    const TSharedPtr<FJsonValue> JsonMapIdField = (*Object)->TryGetField(TEXT("map_id"));
    if (JsonMapIdField.IsValid() && !JsonMapIdField->IsNull())
    {
        MapId_IsSet = TryGetJsonValue(JsonMapIdField, MapId_Optional);
        ParseSuccess &= MapId_IsSet;
    }

    return ParseSuccess;
}

