// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "RallyHereDeveloperAPIBaseModel.h"
#include "RallyHereDeveloperAPIHelpers.h"
#include "DevExpandProperty.generated.h"


/**
 * @brief List of properties Id&#39;s to expand the corresponding name.
 */
UENUM(BlueprintType)
enum class ERHAPI_DevExpandProperty : uint8
{
    All UMETA(ToolTip="List of properties Id&#39;s to expand the corresponding name."),
    LegacyId UMETA(ToolTip="List of properties Id&#39;s to expand the corresponding name."),
};
RALLYHEREDEVELOPERAPI_API FString EnumToString(const ERHAPI_DevExpandProperty& EnumValue);
RALLYHEREDEVELOPERAPI_API bool EnumFromString(const FString& EnumAsString, ERHAPI_DevExpandProperty& EnumValue);
RALLYHEREDEVELOPERAPI_API FStringFormatArg ToStringFormatArg(const ERHAPI_DevExpandProperty& Value);
RALLYHEREDEVELOPERAPI_API void WriteJsonValue(TSharedRef<TJsonWriter<>>& Writer, const ERHAPI_DevExpandProperty& Value);
RALLYHEREDEVELOPERAPI_API bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, ERHAPI_DevExpandProperty& Value);
