// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "AdOpportunities.h"
#include "RallyHereAPIModule.h"
#include "RallyHereAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereAPI::ToStringFormatArg;
using RallyHereAPI::WriteJsonValue;
using RallyHereAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for FRHAPI_AdOpportunities

void FRHAPI_AdOpportunities::WriteJson(TSharedRef<TJsonWriter<>>& Writer) const
{
    Writer->WriteObjectStart();
    Writer->WriteIdentifierPrefix(TEXT("opportunities"));
    RallyHereAPI::WriteJsonValue(Writer, Opportunities);
    Writer->WriteObjectEnd();
}

bool FRHAPI_AdOpportunities::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    const TSharedPtr<FJsonValue> JsonOpportunitiesField = (*Object)->TryGetField(TEXT("opportunities"));
    ParseSuccess &= JsonOpportunitiesField.IsValid() && !JsonOpportunitiesField->IsNull() && TryGetJsonValue(JsonOpportunitiesField, Opportunities);

    return ParseSuccess;
}

