// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "DeleteTicketReason.h"
#include "RallyHereAPIModule.h"
#include "RallyHereAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereAPI::ToStringFormatArg;
using RallyHereAPI::WriteJsonValue;
using RallyHereAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for ERHAPI_DeleteTicketReason
FString EnumToString(const ERHAPI_DeleteTicketReason& Value)
{
	switch (Value)
	{
	case ERHAPI_DeleteTicketReason::Assigned:
		return TEXT("assigned");
	case ERHAPI_DeleteTicketReason::LeftQueue:
		return TEXT("left_queue");
	case ERHAPI_DeleteTicketReason::Timeout:
		return TEXT("timeout");
	case ERHAPI_DeleteTicketReason::PartyChanged:
		return TEXT("party_changed");
	}

	UE_LOG(LogRallyHereAPI, Error, TEXT("Invalid ERHAPI_DeleteTicketReason::Values Value (%d)"), (int)Value);
	return TEXT("");
}

bool EnumFromString(const FString& EnumAsString, ERHAPI_DeleteTicketReason& Value)
{
	static TMap<FString, ERHAPI_DeleteTicketReason> StringToEnum = { 
		{ TEXT("assigned"), ERHAPI_DeleteTicketReason::Assigned },
		{ TEXT("left_queue"), ERHAPI_DeleteTicketReason::LeftQueue },
		{ TEXT("timeout"), ERHAPI_DeleteTicketReason::Timeout },
		{ TEXT("party_changed"), ERHAPI_DeleteTicketReason::PartyChanged },	};

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;
	return Found != nullptr;
}

FStringFormatArg ToStringFormatArg(const ERHAPI_DeleteTicketReason& Value)
{
	return FStringFormatArg(EnumToString(Value));
}

void WriteJsonValue(TSharedRef<TJsonWriter<>>& Writer, const ERHAPI_DeleteTicketReason& Value)
{
	RallyHereAPI::WriteJsonValue(Writer, EnumToString(Value));
}

bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, ERHAPI_DeleteTicketReason& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if (EnumFromString(TmpValue, Value))
			return true;
	}
	return false;
}


