// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "InstanceHealthStatus.h"
#include "RallyHereAPIModule.h"
#include "RallyHereAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereAPI::ToStringFormatArg;
using RallyHereAPI::WriteJsonValue;
using RallyHereAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for ERHAPI_InstanceHealthStatus
FString EnumToString(const ERHAPI_InstanceHealthStatus& Value)
{
	switch (Value)
	{
	case ERHAPI_InstanceHealthStatus::Healthy:
		return TEXT("healthy");
	case ERHAPI_InstanceHealthStatus::Unhealthy:
		return TEXT("unhealthy");
	case ERHAPI_InstanceHealthStatus::Degraded:
		return TEXT("degraded");
	case ERHAPI_InstanceHealthStatus::Unknown:
		return TEXT("unknown");
	}

	UE_LOG(LogRallyHereAPI, Error, TEXT("Invalid ERHAPI_InstanceHealthStatus::Values Value (%d)"), (int)Value);
	return TEXT("");
}

bool EnumFromString(const FString& EnumAsString, ERHAPI_InstanceHealthStatus& Value)
{
	static TMap<FString, ERHAPI_InstanceHealthStatus> StringToEnum = { 
		{ TEXT("healthy"), ERHAPI_InstanceHealthStatus::Healthy },
		{ TEXT("unhealthy"), ERHAPI_InstanceHealthStatus::Unhealthy },
		{ TEXT("degraded"), ERHAPI_InstanceHealthStatus::Degraded },
		{ TEXT("unknown"), ERHAPI_InstanceHealthStatus::Unknown },	};

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;
	return Found != nullptr;
}

FStringFormatArg ToStringFormatArg(const ERHAPI_InstanceHealthStatus& Value)
{
	return FStringFormatArg(EnumToString(Value));
}

void WriteJsonValue(TSharedRef<TJsonWriter<>>& Writer, const ERHAPI_InstanceHealthStatus& Value)
{
	RallyHereAPI::WriteJsonValue(Writer, EnumToString(Value));
}

bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, ERHAPI_InstanceHealthStatus& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if (EnumFromString(TmpValue, Value))
			return true;
	}
	return false;
}


