// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "PlatformIdentityLookupResults.h"
#include "RallyHereAPIModule.h"
#include "RallyHereAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereAPI::ToStringFormatArg;
using RallyHereAPI::WriteJsonValue;
using RallyHereAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for FRHAPI_PlatformIdentityLookupResults

void FRHAPI_PlatformIdentityLookupResults::WriteJson(TSharedRef<TJsonWriter<>>& Writer) const
{
    Writer->WriteObjectStart();
    if (Identity_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("identity"));
        RallyHereAPI::WriteJsonValue(Writer, Identity_Optional);
    }
    Writer->WriteObjectEnd();
}

bool FRHAPI_PlatformIdentityLookupResults::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    const TSharedPtr<FJsonValue> JsonIdentityField = (*Object)->TryGetField(TEXT("identity"));
    if (JsonIdentityField.IsValid() && !JsonIdentityField->IsNull())
    {
        Identity_IsSet = TryGetJsonValue(JsonIdentityField, Identity_Optional);
        ParseSuccess &= Identity_IsSet;
    }

    return ParseSuccess;
}

