// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "PlayerPresence.h"
#include "RallyHereAPIModule.h"
#include "RallyHereAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereAPI::ToStringFormatArg;
using RallyHereAPI::WriteJsonValue;
using RallyHereAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for FRHAPI_PlayerPresence

void FRHAPI_PlayerPresence::WriteJson(TSharedRef<TJsonWriter<>>& Writer) const
{
    Writer->WriteObjectStart();
    if (Status_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("status"));
        RallyHereAPI::WriteJsonValue(Writer, EnumToString(Status_Optional));
    }
    if (Message_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("message"));
        RallyHereAPI::WriteJsonValue(Writer, Message_Optional);
    }
    Writer->WriteIdentifierPrefix(TEXT("platform"));
    RallyHereAPI::WriteJsonValue(Writer, Platform);
    Writer->WriteIdentifierPrefix(TEXT("display_name"));
    RallyHereAPI::WriteJsonValue(Writer, DisplayName);
    if (CustomData_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("custom_data"));
        RallyHereAPI::WriteJsonValue(Writer, CustomData_Optional);
    }
    if (PlayerId_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("player_id"));
        RallyHereAPI::WriteJsonValue(Writer, PlayerId_Optional);
    }
    Writer->WriteIdentifierPrefix(TEXT("player_uuid"));
    RallyHereAPI::WriteJsonValue(Writer, PlayerUuid);
    if (DoNotDisturb_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("do_not_disturb"));
        RallyHereAPI::WriteJsonValue(Writer, DoNotDisturb_Optional);
    }
    if (LastSeen_IsSet)
    {
        Writer->WriteIdentifierPrefix(TEXT("last_seen"));
        RallyHereAPI::WriteJsonValue(Writer, LastSeen_Optional);
    }
    Writer->WriteObjectEnd();
}

bool FRHAPI_PlayerPresence::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    if ((*Object)->HasField(TEXT("status")))
    {
        Status_IsSet = RallyHereAPI::TryGetJsonValue(*Object, TEXT("status"), Status_Optional);
        ParseSuccess &= Status_IsSet;
    }
    if ((*Object)->HasField(TEXT("message")))
    {
        Message_IsSet = RallyHereAPI::TryGetJsonValue(*Object, TEXT("message"), Message_Optional);
        ParseSuccess &= Message_IsSet;
    }
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("platform"), Platform);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("display_name"), DisplayName);
    if ((*Object)->HasField(TEXT("custom_data")))
    {
        CustomData_IsSet = RallyHereAPI::TryGetJsonValue(*Object, TEXT("custom_data"), CustomData_Optional);
        ParseSuccess &= CustomData_IsSet;
    }
    if ((*Object)->HasField(TEXT("player_id")))
    {
        PlayerId_IsSet = RallyHereAPI::TryGetJsonValue(*Object, TEXT("player_id"), PlayerId_Optional);
        ParseSuccess &= PlayerId_IsSet;
    }
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("player_uuid"), PlayerUuid);
    if ((*Object)->HasField(TEXT("do_not_disturb")))
    {
        DoNotDisturb_IsSet = RallyHereAPI::TryGetJsonValue(*Object, TEXT("do_not_disturb"), DoNotDisturb_Optional);
        ParseSuccess &= DoNotDisturb_IsSet;
    }
    if ((*Object)->HasField(TEXT("last_seen")))
    {
        LastSeen_IsSet = RallyHereAPI::TryGetJsonValue(*Object, TEXT("last_seen"), LastSeen_Optional);
        ParseSuccess &= LastSeen_IsSet;
    }

    return ParseSuccess;
}

