// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "QueueConfig.h"
#include "RallyHereAPIModule.h"
#include "RallyHereAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereAPI::ToStringFormatArg;
using RallyHereAPI::WriteJsonValue;
using RallyHereAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for FRHAPI_QueueConfig

void FRHAPI_QueueConfig::WriteJson(TSharedRef<TJsonWriter<>>& Writer) const
{
    Writer->WriteObjectStart();
    Writer->WriteIdentifierPrefix(TEXT("queue_id"));
    RallyHereAPI::WriteJsonValue(Writer, QueueId);
    Writer->WriteIdentifierPrefix(TEXT("active"));
    RallyHereAPI::WriteJsonValue(Writer, Active);
    Writer->WriteIdentifierPrefix(TEXT("ranking_type"));
    RallyHereAPI::WriteJsonValue(Writer, RankingType);
    Writer->WriteIdentifierPrefix(TEXT("num_sides"));
    RallyHereAPI::WriteJsonValue(Writer, NumSides);
    Writer->WriteIdentifierPrefix(TEXT("max_players_per_side"));
    RallyHereAPI::WriteJsonValue(Writer, MaxPlayersPerSide);
    Writer->WriteIdentifierPrefix(TEXT("min_players_per_side"));
    RallyHereAPI::WriteJsonValue(Writer, MinPlayersPerSide);
    Writer->WriteIdentifierPrefix(TEXT("max_queue_group_size"));
    RallyHereAPI::WriteJsonValue(Writer, MaxQueueGroupSize);
    Writer->WriteIdentifierPrefix(TEXT("match_making_template_group_id"));
    RallyHereAPI::WriteJsonValue(Writer, MatchMakingTemplateGroupId);
    Writer->WriteObjectEnd();
}

bool FRHAPI_QueueConfig::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("queue_id"), QueueId);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("active"), Active);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("ranking_type"), RankingType);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("num_sides"), NumSides);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("max_players_per_side"), MaxPlayersPerSide);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("min_players_per_side"), MinPlayersPerSide);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("max_queue_group_size"), MaxQueueGroupSize);
    ParseSuccess &= RallyHereAPI::TryGetJsonValue(*Object, TEXT("match_making_template_group_id"), MatchMakingTemplateGroupId);

    return ParseSuccess;
}

