// NOTE: This file is auto generated by https://github.com/hirezstudios/rally-here-api-generator
// Do not edit the file manually.
//
// Copyright 2018 OpenAPI-Generator Contributors (https://openapi-generator.tech)
// Copyright 2022-2023 RallyHere Interactive
// SPDX-License-Identifier: Apache-2.0


#include "RestrictionEvent.h"
#include "RallyHereAPIModule.h"
#include "RallyHereAPIHelpers.h"
#include "Templates/SharedPointer.h"


using RallyHereAPI::ToStringFormatArg;
using RallyHereAPI::WriteJsonValue;
using RallyHereAPI::TryGetJsonValue;

////////////////////////////////////////////////////
// Implementation for FRHAPI_RestrictionEvent

void FRHAPI_RestrictionEvent::WriteJson(TSharedRef<TJsonWriter<>>& Writer) const
{
	Writer->WriteObjectStart();
	if (Type_IsSet)
	{
		Writer->WriteIdentifierPrefix(TEXT("type"));
		RallyHereAPI::WriteJsonValue(Writer, EnumToString(Type_Optional));
	}
	if (Reason_IsSet)
	{
		Writer->WriteIdentifierPrefix(TEXT("reason"));
		RallyHereAPI::WriteJsonValue(Writer, EnumToString(Reason_Optional));
	}
	if (Expiration_IsSet)
	{
		Writer->WriteIdentifierPrefix(TEXT("expiration"));
		RallyHereAPI::WriteJsonValue(Writer, Expiration_Optional);
	}
	Writer->WriteIdentifierPrefix(TEXT("issuer_type"));
	RallyHereAPI::WriteJsonValue(Writer, EnumToString(IssuerType));
	Writer->WriteIdentifierPrefix(TEXT("issuer"));
	RallyHereAPI::WriteJsonValue(Writer, Issuer);
	if (ReasonDetail_IsSet)
	{
		Writer->WriteIdentifierPrefix(TEXT("reason_detail"));
		RallyHereAPI::WriteJsonValue(Writer, ReasonDetail_Optional);
	}
	Writer->WriteIdentifierPrefix(TEXT("restriction_event_id"));
	RallyHereAPI::WriteJsonValue(Writer, RestrictionEventId);
	Writer->WriteIdentifierPrefix(TEXT("person_id"));
	RallyHereAPI::WriteJsonValue(Writer, PersonId);
	Writer->WriteIdentifierPrefix(TEXT("created"));
	RallyHereAPI::WriteJsonValue(Writer, Created);
	Writer->WriteObjectEnd();
}

bool FRHAPI_RestrictionEvent::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	const TSharedPtr<FJsonValue> JsonTypeField = (*Object)->TryGetField(TEXT("type"));
	if (JsonTypeField.IsValid())
	{
		Type_IsSet = TryGetJsonValue(JsonTypeField, Type_Optional);
		ParseSuccess &= Type_IsSet;
	}
	const TSharedPtr<FJsonValue> JsonReasonField = (*Object)->TryGetField(TEXT("reason"));
	if (JsonReasonField.IsValid())
	{
		Reason_IsSet = TryGetJsonValue(JsonReasonField, Reason_Optional);
		ParseSuccess &= Reason_IsSet;
	}
	const TSharedPtr<FJsonValue> JsonExpirationField = (*Object)->TryGetField(TEXT("expiration"));
	if (JsonExpirationField.IsValid())
	{
		Expiration_IsSet = TryGetJsonValue(JsonExpirationField, Expiration_Optional);
		ParseSuccess &= Expiration_IsSet;
	}
	const TSharedPtr<FJsonValue> JsonIssuerTypeField = (*Object)->TryGetField(TEXT("issuer_type"));
	const bool IssuerType_IsValid = JsonIssuerTypeField.IsValid() && (!JsonIssuerTypeField->IsNull() && TryGetJsonValue(JsonIssuerTypeField, IssuerType));
	ParseSuccess &= IssuerType_IsValid; 
	const TSharedPtr<FJsonValue> JsonIssuerField = (*Object)->TryGetField(TEXT("issuer"));
	const bool Issuer_IsValid = JsonIssuerField.IsValid() && (!JsonIssuerField->IsNull() && TryGetJsonValue(JsonIssuerField, Issuer));
	ParseSuccess &= Issuer_IsValid; 
	const TSharedPtr<FJsonValue> JsonReasonDetailField = (*Object)->TryGetField(TEXT("reason_detail"));
	if (JsonReasonDetailField.IsValid())
	{
		ReasonDetail_IsSet = TryGetJsonValue(JsonReasonDetailField, ReasonDetail_Optional);
		ParseSuccess &= ReasonDetail_IsSet;
	}
	const TSharedPtr<FJsonValue> JsonRestrictionEventIdField = (*Object)->TryGetField(TEXT("restriction_event_id"));
	const bool RestrictionEventId_IsValid = JsonRestrictionEventIdField.IsValid() && (!JsonRestrictionEventIdField->IsNull() && TryGetJsonValue(JsonRestrictionEventIdField, RestrictionEventId));
	ParseSuccess &= RestrictionEventId_IsValid; 
	const TSharedPtr<FJsonValue> JsonPersonIdField = (*Object)->TryGetField(TEXT("person_id"));
	const bool PersonId_IsValid = JsonPersonIdField.IsValid() && (!JsonPersonIdField->IsNull() && TryGetJsonValue(JsonPersonIdField, PersonId));
	ParseSuccess &= PersonId_IsValid; 
	const TSharedPtr<FJsonValue> JsonCreatedField = (*Object)->TryGetField(TEXT("created"));
	const bool Created_IsValid = JsonCreatedField.IsValid() && (!JsonCreatedField->IsNull() && TryGetJsonValue(JsonCreatedField, Created));
	ParseSuccess &= Created_IsValid; 

	return ParseSuccess;
}

