name: Generate Documentation
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  generate:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install System Dependencies
      run: |
        sudo apt install -y doxygen
    - uses: actions/setup-node@v4
      with:
        node-version: '14'
    - name: Install Node Dependencies
      run: |
        npm install moxygen
    - name: Run Generate Script
      run: |
        Documentation/generate.bash
    - name: Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email "builder@rallyhere.gg"
        git config user.name "RallyHereBuilder"
        git pull
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Generate Documentation" && git push)
